title = "Test/Example site"
subtitle = "Site to test theme, css, layout, rendering rules, etc."
author = "Aliaksei Yaletski (Tiendil)"

[[menu]]
  type = "blog"
  name = "Blog"

[[menu]]
  type = "feed"
  name = ""
  css_classes = "ti ti-rss"
  tooltip = "RSS Feed"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-github"
  name = ""
  url = "https://github.com/Tiendil/brigid"
  tooltip = "GitHub"

[license]
url = "https://example.com"
name = "License name"

[tags_translations]
example = "example"
wide = "wide"
basic = "basic"
images = "images"
snippets = "snippets"
languages = "languages"

[theme_translations]
