title = "Сайт-приме"
subtitle = "Сайт чтобы тестить тему, CSS, лэйаут, правила рендера, etc."
author = "Елецкий Алексей (Tiendil)"

[[menu]]
  type = "blog"
  name = "Блог"

[[menu]]
  type = "feed"
  name = ""
  css_classes = "ti ti-rss"
  tooltip = "RSS Feed"

[[menu]]
  type = "external"
  css_classes = "ti ti-brand-github"
  name = ""
  url = "https://github.com/Tiendil/brigid"
  tooltip = "GitHub"


[license]
url = "https://example.com"
name = "Название лицензии"

[tags_translations]
example = "пример"
wide = "широкая страница"
basic = "базовый рендер"
images = "картинки"
snippets = "сниппеты"
languages = "языки/переводы"

[theme_translations]
